import os
from typing import Any

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise ValueError("GROQ_API_KEY not found in environment variables.")

client = Groq(api_key=GROQ_API_KEY)
MODEL_NAME = "llama-3.1-8b-instant"

SYSTEM_TEMPLATE = """\
You are LegalAI, a helpful and expert Indian legal assistant. 
Your goal is to explain Indian laws and provide guidance on legal situations in plain, accessible language.

GUIDELINES:
1. USE CONTEXT: If relevant legal context is provided below, prioritize it. Cite the specific Acts and Sections.
2. GENERAL KNOWLEDGE: If the retrieved context is insufficient to answer "daily life" legal questions (e.g., workplace issues, tenant rights, consumer complaints), use your general knowledge of Indian Law to provide helpful guidance.
3. BE PRACTICAL: Explain what steps a user should take (e.g., "send a legal notice", "approach the labor commissioner").
4. ACCURACY: Do not fabricate specific section numbers. If you are unsure of a specific section, state the general legal principle instead.
5. DISCLAIMER: Always remind the user that your advice is for informational purposes and they should consult a qualified lawyer for critical matters.

RETRIEVED LEGAL CONTEXT:
{context_block}"""


def _build_context_block(retrieved_contexts: list[Any]) -> str:
    if not retrieved_contexts:
        return "No specific laws were found in the database."
    lines = []
    for idx, doc in enumerate(retrieved_contexts, start=1):
        lines.append(f"--- LAW {idx} ---")
        lines.append(f"Act: {doc.get('act_name', 'Unknown')}")
        lines.append(f"Section {doc.get('section', '?')}: {doc.get('title', '')}")
        lines.append(f"Content: {doc.get('content', '')}")
        lines.append("")
    return "\n".join(lines)


def generate_legal_response_stream(
    user_query: str,
    retrieved_contexts: list[Any],
    chat_history: list[dict] | None = None,
):
    """
    Streaming version of generate_legal_response.
    Yields chunks of text as they are generated by Groq.
    """
    context_block = _build_context_block(retrieved_contexts)
    system_prompt = SYSTEM_TEMPLATE.format(context_block=context_block)

    messages: list[dict] = [{"role": "system", "content": system_prompt}]

    # Append prior conversation turns
    for turn in (chat_history or []):
        role = turn.get("role", "")
        content = turn.get("content", "")
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})

    messages.append({"role": "user", "content": user_query})

    try:
        completion = client.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            temperature=0.3,
            stream=True,  # Enable streaming
        )
        for chunk in completion:
            content = chunk.choices[0].delta.content
            if content:
                yield content
    except Exception as exc:
        yield f"Error communicating with AI: {exc}"


def generate_legal_response(
    user_query: str,
    retrieved_contexts: list[Any],
    chat_history: list[dict] | None = None,
) -> str:
    """
    Non-streaming version of generate_legal_response.
    Useful for background tasks or simple API calls.
    """
    context_block = _build_context_block(retrieved_contexts)
    system_prompt = SYSTEM_TEMPLATE.format(context_block=context_block)

    messages: list[dict] = [{"role": "system", "content": system_prompt}]
    for turn in (chat_history or []):
        role = turn.get("role", "")
        content = turn.get("content", "")
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})

    messages.append({"role": "user", "content": user_query})

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            temperature=0.3,
        )
        return response.choices[0].message.content or ""
    except Exception as exc:
        return f"Error communicating with AI: {exc}"


def explain_legal_document_with_ai(text: str) -> tuple[str, list[str]]:
    """
    Summarize a legal document and extract key highlights using Groq.
    """
    prompt = f"""
    You are a legal expert specializing in Indian law. 
    Summarize the following legal document in plain, simple language for a non-lawyer.
    Identify the type of document, key parties involved, any critical deadlines, and the main request or allegation.
    
    Output format:
    SUMMARY: [A concise 2-3 paragraph summary]
    HIGHLIGHTS:
    - [Highlight 1]
    - [Highlight 2]
    - [Highlight 3]
    - [Highlight 4]
    
    DOCUMENT TEXT:
    {text[:4000]}
    """

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
        )
        raw_output = response.choices[0].message.content or ""
        
        # Simple parsing logic
        summary = "No summary generated."
        highlights = []
        
        if "SUMMARY:" in raw_output:
            parts = raw_output.split("HIGHLIGHTS:")
            summary = parts[0].replace("SUMMARY:", "").strip()
            if len(parts) > 1:
                highlights = [line.strip("- ").strip() for line in parts[1].strip().split("\n") if line.strip()]
        
        return summary, highlights[:5]
    except Exception as exc:
        return f"Error explaining document: {exc}", ["Verification failed due to AI error."]


def generate_legal_draft_ai(draft_type: str, inputs: dict) -> str:
    """
    Generate a formal legal draft (RTI, ITR, etc.) using AI.
    """
    system_prompt = """
    You are a professional Indian legal drafter. Your objective is to help the user draft formal legal documents flawlessly.
    
    IMPORTANT FORMATTING RULES: 
    - DO NOT use markdown symbols (#, *, **).
    - JUSTIFICATION: Body text should be structured and professional.
    - HEADERS: Center the main title of the document.
    - ALIGNMENT: Keep addresses and "To," sections left-aligned for a clean look.
    - SPACING: Use double newlines between formal sections.
    - SIGNATURES: Ensure clear lines for signatures at the bottom.
    
    RULES FOR DRAFTING:
    1. Use a formal, respectful tone.
    2. Maintain the specific legal structure requested (e.g., RTI Application format).
    3. Ensure all user-provided variables are correctly placed.
    """

    if "RTI" in draft_type.upper():
        prompt = f"""
        Generate a formal RTI Application based on the following details and the standard Indian RTI format.
        
        TEMPLATE TO FOLLOW:
        APPLICATION UNDER SECTION 6(1) OF THE RIGHT TO INFORMATION ACT, 2005
        To, The Public Information Officer (PIO), [DEPARTMENT_NAME], [DEPARTMENT_ADDRESS].
        1. Full Name of the Applicant: [APPLICANT_NAME]
        2. Full Address of the Applicant: [APPLICANT_ADDRESS]
        3. Contact Details: Ph: [APPLICANT_PHONE] / Email: [APPLICANT_EMAIL]
        4. Details of Information Requested: [RTI_QUESTIONS]
        5. Period: [TIME_PERIOD]
        6. Fee Details: [FEE_INFO]
        7. Declaration: I am a citizen of India.
        
        USER INPUTS:
        {inputs}
        """
    elif "RENT AGREEMENT" in draft_type.upper():
        prompt = f"""
        Generate a formal Rent Agreement based on the provided details. 
        IMPORTANT: Default the tenancy period to 11 months unless specified otherwise.
        
        TEMPLATE TO FOLLOW:
        RENT AGREEMENT
        This Rent Agreement is made on [DAY] [MONTH] [YEAR] at [CITY].
        BETWEEN [LANDLORD_NAME] (Landlord) AND [TENANT_NAME] (Tenant).
        Property: [RENTAL_PROPERTY_ADDRESS]
        1. TERM: 11 months from [START_DATE].
        2. RENT: Rs. [MONTHLY_RENT_AMOUNT]/- per month.
        3. SECURITY DEPOSIT: Rs. [SECURITY_DEPOSIT_AMOUNT]/-.
        4. USAGE: Residential purposes only.
        5. TERMINATION: [NOTICE_PERIOD] month notice.
        
        USER INPUTS:
        {inputs}
        """
    elif "ITR" in draft_type.upper() or "INCOME TAX" in draft_type.upper():
        prompt = f"""
        Generate a formal Reply to an Income Tax Notice based on these inputs.
        
        TEMPLATE TO FOLLOW:
        To, The Assessing Officer / Income Tax Officer, Ward / Circle [WARD_OR_CIRCLE_NUMBER], Income Tax Department, [CITY].
        SUBJECT: Reply to Notice under Section [SECTION_OF_NOTICE] of the Income Tax Act, 1961 for Assessment Year [ASSESSMENT_YEAR].
        REF: PAN: [PAN_NUMBER], Notice DIN/Ref: [NOTICE_REF], Date: [DATE_OF_NOTICE].
        
        Structure the body with factual points:
        1. ITR Filing Details ([DATE_OF_FILING_ITR], [ITR_ACK_NUMBER])
        2. Description of Issue ([ISSUE_DESCRIPTION])
        3. Factual Defense ([FACTUAL_DEFENSE])
        
        End with a list of Enclosures.
        
        USER INPUTS:
        {inputs}
        """
    else:
        # Default to ITR or other legal representations
        prompt = f"""
        Generate a formal legal representation (e.g., Reply to Income Tax Notice) based on these inputs.
        Ensure it is addressed to the "Assessing Officer", includes a "SUBJECT:" line, and ends with a "Verification" section.
        
        USER INPUTS:
        {inputs}
        """

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            temperature=0.2,
        )
        return response.choices[0].message.content or ""
    except Exception as exc:
        return f"Error generating draft: {exc}"